export const resultados = [
    'Todos', 'Proliferativo', 'Moderado', 'Leve', 'Sin Afección'
]

export const afecciones = [
    'Todas',
    'DMAE Humeda',
    'DMAE Seca',
    'Retinopatía Diabética'
]

export const reports = [
    { id: 'c496f7', fecha: '21/05/2025', hora: '06:14 AM', edad: 33, afeccion: 'DMAE Humeda', ojo: 'Derecho', resultado: 'Proliferativo' },
    { id: '4cd866', fecha: '04/05/2025', hora: '04:38 PM', edad: 66, afeccion: 'DMAE Seca', ojo: 'Izquierdo', resultado: 'Proliferativo' },
    { id: '2f2770', fecha: '01/05/2025', hora: '12:35 AM', edad: 28, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Moderado' },
    { id: '44dfc1', fecha: '24/05/2025', hora: '06:45 AM', edad: 88, afeccion: 'DMAE Humeda', ojo: 'Derecho', resultado: 'Leve' },
    { id: 'aacfcb', fecha: '20/05/2025', hora: '08:44 PM', edad: 55, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Leve' },
    { id: 'd01787', fecha: '08/05/2025', hora: '05:26 PM', edad: 64, afeccion: 'Retinopatía Diabética', ojo: 'Izquierdo', resultado: 'Proliferativo' },
    { id: '8da49a', fecha: '08/05/2025', hora: '07:28 AM', edad: 42, afeccion: 'Retinopatía Diabética', ojo: 'Izquierdo', resultado: 'Sin Afeccion' },
    { id: '5484b0', fecha: '05/05/2025', hora: '06:17 PM', edad: 26, afeccion: 'DMAE Seca', ojo: 'Izquierdo', resultado: 'Sin Afeccion' },
    { id: '3707a9', fecha: '24/05/2025', hora: '12:48 AM', edad: 23, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Sin Afeccion' },
    { id: '7c2861', fecha: '20/05/2025', hora: '05:44 AM', edad: 47, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Leve' },
    { id: 'ec3030', fecha: '22/05/2025', hora: '01:21 PM', edad: 55, afeccion: 'DMAE Seca', ojo: 'Izquierdo', resultado: 'Leve' },
    { id: '5c9b55', fecha: '24/05/2025', hora: '08:09 AM', edad: 28, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Proliferativo' },
    { id: 'c7378f', fecha: '29/05/2025', hora: '06:48 AM', edad: 47, afeccion: 'Retinopatía Diabética', ojo: 'Izquierdo', resultado: 'Sin Afeccion' },
    { id: 'bf81bd', fecha: '12/05/2025', hora: '10:06 AM', edad: 30, afeccion: 'DMAE Seca', ojo: 'Izquierdo', resultado: 'Proliferativo' },
    { id: '1b32a4', fecha: '03/05/2025', hora: '02:24 AM', edad: 66, afeccion: 'DMAE Seca', ojo: 'Izquierdo', resultado: 'Proliferativo' },
    { id: '8f03f9', fecha: '19/05/2025', hora: '03:22 AM', edad: 53, afeccion: 'DMAE Humeda', ojo: 'Derecho', resultado: 'Proliferativo' },
    { id: '006644', fecha: '14/05/2025', hora: '11:38 AM', edad: 76, afeccion: 'DMAE Humeda', ojo: 'Izquierdo', resultado: 'Moderado' },
    { id: '3d99fe', fecha: '02/05/2025', hora: '08:51 AM', edad: 64, afeccion: 'DMAE Humeda', ojo: 'Derecho', resultado: 'Sin Afeccion' },
    { id: 'c14b33', fecha: '01/05/2025', hora: '01:46 AM', edad: 38, afeccion: 'Retinopatía Diabética', ojo: 'Derecho', resultado: 'Sin Afeccion' },
    { id: 'a11288', fecha: '03/05/2025', hora: '02:34 PM', edad: 65, afeccion: 'Retinopatía Diabética', ojo: 'Izquierdo', resultado: 'Moderado' }
];

export const dataPointsMocks = [
    { lat: 18.8498, lng: -97.1039, name: 'Laura Fernández Fernández', resultado: 'Proliferativo', afeccion: 'DMAE Seca', id: 'P001', fechaCreacion: new Date('2025-02-09') },
    { lat: 18.8477, lng: -97.1014, name: 'Francisco Pérez Fernández', resultado: 'Leve', afeccion: 'Retinopatía Diabética', id: 'P002', fechaCreacion: new Date('2025-03-22') },
    { lat: 18.8512, lng: -97.1056, name: 'Lucía Ramírez Castro', resultado: 'Moderado', afeccion: 'DMAE Húmeda', id: 'P003', fechaCreacion: new Date('2025-03-18') },
    { lat: 18.8536, lng: -97.1069, name: 'Fernando Torres Gómez', resultado: 'Proliferativo', afeccion: 'Retinopatía Diabética', id: 'P004', fechaCreacion: new Date('2025-03-07') },
    { lat: 18.8452, lng: -97.1022, name: 'Raúl Ramírez López', resultado: 'Sin Afección', afeccion: 'DMAE Húmeda', id: 'P005', fechaCreacion: new Date('2025-03-01') },
    { lat: 18.8501, lng: -97.1104, name: 'Andrea Castro López', resultado: 'Leve', afeccion: 'Retinopatía Diabética', id: 'P006', fechaCreacion: new Date('2025-05-12') },
    { lat: 18.8509, lng: -97.1007, name: 'Laura Pérez Ruiz', resultado: 'Moderado', afeccion: 'DMAE Seca', id: 'P007', fechaCreacion: new Date('2025-04-11') },
    { lat: 18.8459, lng: -97.0978, name: 'Pedro Martínez Torres', resultado: 'Proliferativo', afeccion: 'DMAE Húmeda', id: 'P008', fechaCreacion: new Date('2025-04-27') },
    { lat: 18.8520, lng: -97.1001, name: 'Rosa Castro López', resultado: 'Leve', afeccion: 'Retinopatía Diabética', id: 'P009', fechaCreacion: new Date('2025-02-08') },
    { lat: 18.8490, lng: -97.1025, name: 'Ana Castro Fernández', resultado: 'Sin Afección', afeccion: 'DMAE Seca', id: 'P010', fechaCreacion: new Date('2025-01-17') },

    { lat: 18.8513, lng: -97.0981, name: 'Lucía Castro Ruiz', resultado: 'Proliferativo', afeccion: 'DMAE Húmeda', id: 'P011', fechaCreacion: new Date('2025-01-28') },
    { lat: 18.8455, lng: -97.1060, name: 'Raúl Ruiz Gómez', resultado: 'Moderado', afeccion: 'Retinopatía Diabética', id: 'P012', fechaCreacion: new Date('2025-04-18') },
    { lat: 18.8429, lng: -97.1044, name: 'Lucía Fernández Martínez', resultado: 'Leve', afeccion: 'DMAE Seca', id: 'P013', fechaCreacion: new Date('2025-02-09') },
    { lat: 18.8518, lng: -97.1087, name: 'Pedro Ruiz Fernández', resultado: 'Sin Afección', afeccion: 'DMAE Húmeda', id: 'P014', fechaCreacion: new Date('2025-02-17') },
    { lat: 18.8531, lng: -97.1075, name: 'Raúl Pérez Ramírez', resultado: 'Moderado', afeccion: 'Retinopatía Diabética', id: 'P015', fechaCreacion: new Date('2025-05-12') },

    { lat: 18.8484, lng: -97.1070, name: 'Laura Castro Fernández', resultado: 'Leve', afeccion: 'DMAE Seca', id: 'P016', fechaCreacion: new Date('2025-03-10') },
    { lat: 18.8468, lng: -97.1108, name: 'Raúl Pérez López', resultado: 'Sin Afección', afeccion: 'DMAE Húmeda', id: 'P017', fechaCreacion: new Date('2025-02-06') },
    { lat: 18.8547, lng: -97.1089, name: 'Lucía Castro Fernández', resultado: 'Proliferativo', afeccion: 'Retinopatía Diabética', id: 'P018', fechaCreacion: new Date('2025-02-09') },
    { lat: 18.8553, lng: -97.0997, name: 'Pedro Ruiz Martínez', resultado: 'Leve', afeccion: 'DMAE Seca', id: 'P019', fechaCreacion: new Date('2025-02-19') },
    { lat: 18.8505, lng: -97.0983, name: 'Raúl Ruiz Pérez', resultado: 'Moderado', afeccion: 'DMAE Húmeda', id: 'P020', fechaCreacion: new Date('2025-04-10') }
];

export const doctores = [
    {
        clave: 'D001',
        nombre: 'Carlos',
        apellidoPaterno: 'Gómez',
        apellidoMaterno: 'Hernández',
        fechaNacimiento: '12/05/1980',
        fechaAlta: '01/01/2025',
        telefono: '1234567890',
        genero: 'Masculino',
        codigoPostal: '94300',
        direccion: 'Calle Reforma #123, Centro, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D002',
        nombre: 'María',
        apellidoPaterno: 'Pérez',
        apellidoMaterno: 'Ramírez',
        fechaNacimiento: '08/11/1975',
        fechaAlta: '01/02/2025',
        telefono: '0987654321',
        genero: 'Femenino',
        codigoPostal: '94320',
        direccion: 'Av. Circunvalación #456, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D003',
        nombre: 'Luis',
        apellidoPaterno: 'Martínez',
        apellidoMaterno: 'López',
        fechaNacimiento: '21/03/1990',
        fechaAlta: '01/03/2025',
        telefono: '2143658709',
        genero: 'Masculino',
        codigoPostal: '94340',
        direccion: 'Blvd. Colón #789, Norte, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D004',
        nombre: 'Sofía',
        apellidoPaterno: 'García',
        apellidoMaterno: 'Cruz',
        fechaNacimiento: '30/07/1985',
        telefono: '1223344556',
        fechaAlta: '01/04/2025',
        genero: 'Femenino',
        codigoPostal: '94360',
        direccion: 'Calle Sur 4 #321, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D005',
        nombre: 'Jorge',
        apellidoPaterno: 'Ramírez',
        apellidoMaterno: 'Torres',
        fechaNacimiento: '15/01/1978',
        fechaAlta: '01/05/2025',
        telefono: '5667788990',
        genero: 'Masculino',
        codigoPostal: '94380',
        direccion: 'Calle Poniente 12 #654, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D006',
        nombre: 'Ana',
        apellidoPaterno: 'López',
        apellidoMaterno: 'Rivera',
        fechaNacimiento: '05/02/1995',
        telefono: '0998877665',
        fechaAlta: '01/06/2025',
        genero: 'Femenino',
        codigoPostal: '94400',
        direccion: 'Calle Oriente 2 #987, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D007',
        nombre: 'Roberto',
        apellidoPaterno: 'Vázquez',
        apellidoMaterno: 'Martínez',
        fechaNacimiento: '10/06/1988',
        fechaAlta: '01/07/2025',
        telefono: '0192838475',
        genero: 'Masculino',
        codigoPostal: '94410',
        direccion: 'Calle Norte 8 #456, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D008',
        nombre: 'Gabriela',
        apellidoPaterno: 'Hernández',
        apellidoMaterno: 'Morales',
        fechaNacimiento: '22/08/1983',
        fechaAlta: '01/08/2025',
        telefono: '0561804719',
        genero: 'Femenino',
        codigoPostal: '94420',
        direccion: 'Calle Oriente 4 #321, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D009',
        nombre: 'Fernando',
        apellidoPaterno: 'Ortega',
        apellidoMaterno: 'Sánchez',
        fechaNacimiento: '17/04/1991',
        fechaAlta: '01/09/2025',
        telefono: '9291040194',
        genero: 'Masculino',
        codigoPostal: '94430',
        direccion: 'Calle Poniente 6 #789, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D010',
        nombre: 'Laura',
        apellidoPaterno: 'Mendoza',
        apellidoMaterno: 'Salas',
        fechaNacimiento: '29/12/1982',
        fechaAlta: '01/10/2025',
        telefono: '129091244',
        genero: 'Femenino',
        codigoPostal: '94440',
        direccion: 'Calle Sur 10 #432, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D011',
        nombre: 'Alberto',
        apellidoPaterno: 'Rivas',
        apellidoMaterno: 'Gómez',
        fechaNacimiento: '07/09/1979',
        fechaAlta: '01/11/2025',
        telefono: '312312980',
        genero: 'Masculino',
        codigoPostal: '94450',
        direccion: 'Calle Reforma #101, Centro, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'D012',
        nombre: 'Daniela',
        apellidoPaterno: 'Núñez',
        apellidoMaterno: 'Díaz',
        fechaNacimiento: '02/03/1993',
        fechaAlta: '01/12/2025',
        telefono: '0192941801',
        genero: 'Femenino',
        codigoPostal: '94460',
        direccion: 'Calle Colón #333, Norte, Orizaba',
        estado: 'Veracruz'
    }
];

export const generos = [
    'Masculino',
    'Femenino',
]

export const patients = [
    {
        clave: 'P001',
        nombre: 'Laura',
        apellidoPaterno: 'Fernández',
        apellidoMaterno: 'Fernández',
        fechaNacimiento: '23/02/2057',
        edad: 32,
        genero: 'Masculino',
        ocupacion: 'Técnico',
        correo: 'laura.fernández@domain.com',
        telefono: '2295171867',
        codigoPostal: '94333',
        direccion: 'Calle Oriente #56, Orizaba',
        estado: 'Puebla'
    },
    {
        clave: 'P002',
        nombre: 'Francisco',
        apellidoPaterno: 'Pérez',
        apellidoMaterno: 'Fernández',
        fechaNacimiento: '07/09/2057',
        edad: 32,
        genero: 'Femenino',
        ocupacion: 'Técnico',
        correo: 'francisco.pérez@domain.com',
        telefono: '2292837531',
        codigoPostal: '94384',
        direccion: 'Calle Sur #532, Orizaba',
        estado: 'Tabasco'
    },
    {
        clave: 'P003',
        nombre: 'Lucía',
        apellidoPaterno: 'Ramírez',
        apellidoMaterno: 'Castro',
        fechaNacimiento: '26/02/2054',
        edad: 29,
        genero: 'Femenino',
        ocupacion: 'Ingeniero',
        correo: 'lucía.ramírez@domain.com',
        telefono: '2297044885',
        codigoPostal: '94326',
        direccion: 'Calle Reforma #449, Orizaba',
        estado: 'Oaxaca'
    },
    {
        clave: 'P004',
        nombre: 'Fernando',
        apellidoPaterno: 'Torres',
        apellidoMaterno: 'Gómez',
        fechaNacimiento: '20/07/2059',
        edad: 34,
        genero: 'Femenino',
        ocupacion: 'Ingeniero',
        correo: 'fernando.torres@domain.com',
        telefono: '2291365574',
        codigoPostal: '94341',
        direccion: 'Calle Oriente #927, Orizaba',
        estado: 'Chiapas'
    },
    {
        clave: 'P005',
        nombre: 'Raúl',
        apellidoPaterno: 'Ramírez',
        apellidoMaterno: 'López',
        fechaNacimiento: '03/05/2051',
        edad: 26,
        genero: 'Femenino',
        ocupacion: 'Doctora',
        correo: 'raúl.ramírez@domain.com',
        telefono: '2299106370',
        codigoPostal: '94396',
        direccion: 'Calle Reforma #219, Orizaba',
        estado: 'Chiapas'
    },
    {
        clave: 'P006',
        nombre: 'Andrea',
        apellidoPaterno: 'Castro',
        apellidoMaterno: 'López',
        fechaNacimiento: '16/08/2048',
        edad: 23,
        genero: 'Masculino',
        ocupacion: 'Profesor',
        correo: 'andrea.castro@domain.com',
        telefono: '2293316200',
        codigoPostal: '94364',
        direccion: 'Calle Oriente #155, Orizaba',
        estado: 'Chiapas'
    },
    {
        clave: 'P007',
        nombre: 'Laura',
        apellidoPaterno: 'Pérez',
        apellidoMaterno: 'Ruiz',
        fechaNacimiento: '14/11/2067',
        edad: 42,
        genero: 'Masculino',
        ocupacion: 'Doctora',
        correo: 'laura.pérez@domain.com',
        telefono: '2296869076',
        codigoPostal: '94357',
        direccion: 'Calle Sur #52, Orizaba',
        estado: 'Oaxaca'
    },
    {
        clave: 'P008',
        nombre: 'Pedro',
        apellidoPaterno: 'Martínez',
        apellidoMaterno: 'Torres',
        fechaNacimiento: '10/04/2064',
        edad: 39,
        genero: 'Femenino',
        ocupacion: 'Enfermera',
        correo: 'pedro.martínez@domain.com',
        telefono: '2299327403',
        codigoPostal: '94342',
        direccion: 'Calle Reforma #722, Orizaba',
        estado: 'Puebla'
    },
    {
        clave: 'P009',
        nombre: 'Rosa',
        apellidoPaterno: 'Castro',
        apellidoMaterno: 'López',
        fechaNacimiento: '28/01/2061',
        edad: 36,
        genero: 'Masculino',
        ocupacion: 'Abogado',
        correo: 'rosa.castro@domain.com',
        telefono: '2296160532',
        codigoPostal: '94343',
        direccion: 'Calle Sur #234, Orizaba',
        estado: 'Tabasco'
    },
    {
        clave: 'P010',
        nombre: 'Ana',
        apellidoPaterno: 'Castro',
        apellidoMaterno: 'Fernández',
        fechaNacimiento: '06/12/2064',
        edad: 39,
        genero: 'Masculino',
        ocupacion: 'Ingeniero',
        correo: 'ana.castro@domain.com',
        telefono: '2292760822',
        codigoPostal: '94322',
        direccion: 'Calle Sur #751, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'P011',
        nombre: 'Lucía',
        apellidoPaterno: 'Castro',
        apellidoMaterno: 'Ruiz',
        fechaNacimiento: '12/06/2047',
        edad: 22,
        genero: 'Masculino',
        ocupacion: 'Abogado',
        correo: 'lucía.castro@domain.com',
        telefono: '2292757069',
        codigoPostal: '94331',
        direccion: 'Calle Oriente #812, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'P012',
        nombre: 'Raúl',
        apellidoPaterno: 'Ruiz',
        apellidoMaterno: 'Gómez',
        fechaNacimiento: '31/05/2060',
        edad: 35,
        genero: 'Masculino',
        ocupacion: 'Técnico',
        correo: 'raúl.ruiz@domain.com',
        telefono: '2294461174',
        codigoPostal: '94384',
        direccion: 'Calle Oriente #386, Orizaba',
        estado: 'Puebla'
    },
    {
        clave: 'P013',
        nombre: 'Lucía',
        apellidoPaterno: 'Fernández',
        apellidoMaterno: 'Martínez',
        fechaNacimiento: '07/01/2049',
        edad: 24,
        genero: 'Masculino',
        ocupacion: 'Médico',
        correo: 'lucía.fernández@domain.com',
        telefono: '2295537683',
        codigoPostal: '94331',
        direccion: 'Calle Reforma #679, Orizaba',
        estado: 'Tabasco'
    },
    {
        clave: 'P014',
        nombre: 'Pedro',
        apellidoPaterno: 'Ruiz',
        apellidoMaterno: 'Fernández',
        fechaNacimiento: '02/08/2066',
        edad: 41,
        genero: 'Masculino',
        ocupacion: 'Profesor',
        correo: 'pedro.ruiz@domain.com',
        telefono: '2298808998',
        codigoPostal: '94302',
        direccion: 'Calle Reforma #701, Orizaba',
        estado: 'Veracruz'
    },
    {
        clave: 'P015',
        nombre: 'Laura',
        apellidoPaterno: 'Gómez',
        apellidoMaterno: 'Gómez',
        fechaNacimiento: '12/11/2053',
        edad: 28,
        genero: 'Masculino',
        ocupacion: 'Doctora',
        correo: 'laura.gómez@domain.com',
        telefono: '2295788093',
        codigoPostal: '94325',
        direccion: 'Calle Reforma #874, Orizaba',
        estado: 'Oaxaca'
    },
    {
        clave: 'P016',
        nombre: 'Raúl',
        apellidoPaterno: 'Pérez',
        apellidoMaterno: 'Ramírez',
        fechaNacimiento: '29/06/2072',
        edad: 47,
        genero: 'Masculino',
        ocupacion: 'Ingeniero',
        correo: 'raúl.pérez@domain.com',
        telefono: '2297169800',
        codigoPostal: '94321',
        direccion: 'Calle Reforma #82, Orizaba',
        estado: 'Chiapas'
    },
    {
        clave: 'P017',
        nombre: 'Laura',
        apellidoPaterno: 'Castro',
        apellidoMaterno: 'Fernández',
        fechaNacimiento: '15/12/2058',
        edad: 33,
        genero: 'Femenino',
        ocupacion: 'Profesor',
        correo: 'laura.castro@domain.com',
        telefono: '2293039273',
        codigoPostal: '94360',
        direccion: 'Calle Reforma #833, Orizaba',
        estado: 'Tabasco'
    },
    {
        clave: 'P018',
        nombre: 'Pedro',
        apellidoPaterno: 'Ruiz',
        apellidoMaterno: 'Torres',
        fechaNacimiento: '23/01/2046',
        edad: 21,
        genero: 'Masculino',
        ocupacion: 'Contador',
        correo: 'pedro.ruiz@domain.com',
        telefono: '2292753709',
        codigoPostal: '94313',
        direccion: 'Calle Reforma #455, Orizaba',
        estado: 'Oaxaca'
    },
    {
        clave: 'P019',
        nombre: 'Jorge',
        apellidoPaterno: 'Gómez',
        apellidoMaterno: 'Ruiz',
        fechaNacimiento: '08/10/2051',
        edad: 26,
        genero: 'Masculino',
        ocupacion: 'Enfermera',
        correo: 'jorge.gómez@domain.com',
        telefono: '2296872362',
        codigoPostal: '94301',
        direccion: 'Calle Oriente #722, Orizaba',
        estado: 'Chiapas'
    },
    {
        clave: 'P020',
        nombre: 'Jorge',
        apellidoPaterno: 'Fernández',
        apellidoMaterno: 'Hernández',
        fechaNacimiento: '07/03/2070',
        edad: 45,
        genero: 'Masculino',
        ocupacion: 'Profesor',
        correo: 'jorge.fernández@domain.com',
        telefono: '2295408332',
        codigoPostal: '94331',
        direccion: 'Calle Sur #945, Orizaba',
        estado: 'Veracruz'
    }
];

export const inspecciones = [
    {
        id: 'I001',
        fecha: '03/02/2025',
        hora: '14:02',
        edad: 29,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I002',
        fecha: '21/01/2025',
        hora: '14:04',
        edad: 77,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I003',
        fecha: '29/03/2025',
        hora: '8:59',
        edad: 42,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P009'
    },
    {
        id: 'I004',
        fecha: '26/02/2025',
        hora: '9:54',
        edad: 59,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P006'
    },
    {
        id: 'I005',
        fecha: '05/02/2025',
        hora: '9:52',
        edad: 70,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P010'
    },
    {
        id: 'I006',
        fecha: '02/05/2025',
        hora: '9:38',
        edad: 62,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P012'
    },
    {
        id: 'I007',
        fecha: '13/04/2025',
        hora: '15:30',
        edad: 60,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I008',
        fecha: '01/01/2025',
        hora: '15:24',
        edad: 69,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P005'
    },
    {
        id: 'I009',
        fecha: '28/02/2025',
        hora: '8:48',
        edad: 74,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P020'
    },
    {
        id: 'I010',
        fecha: '16/02/2025',
        hora: '14:39',
        edad: 60,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I011',
        fecha: '11/04/2025',
        hora: '12:25',
        edad: 69,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I012',
        fecha: '03/05/2025',
        hora: '17:28',
        edad: 68,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P014'
    },
    {
        id: 'I013',
        fecha: '16/03/2025',
        hora: '10:47',
        edad: 41,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P012'
    },
    {
        id: 'I014',
        fecha: '01/05/2025',
        hora: '8:54',
        edad: 71,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P008'
    },
    {
        id: 'I015',
        fecha: '28/01/2025',
        hora: '16:47',
        edad: 42,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P015'
    },
    {
        id: 'I016',
        fecha: '21/01/2025',
        hora: '16:38',
        edad: 50,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P012'
    },
    {
        id: 'I017',
        fecha: '03/05/2025',
        hora: '13:50',
        edad: 29,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P003'
    },
    {
        id: 'I018',
        fecha: '02/04/2025',
        hora: '9:39',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P001'
    },
    {
        id: 'I019',
        fecha: '13/04/2025',
        hora: '10:39',
        edad: 52,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P019'
    },
    {
        id: 'I020',
        fecha: '07/05/2025',
        hora: '17:21',
        edad: 18,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P011'
    },
    {
        id: 'I021',
        fecha: '03/02/2025',
        hora: '8:16',
        edad: 39,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P015'
    },
    {
        id: 'I022',
        fecha: '05/01/2025',
        hora: '18:39',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P011'
    },
    {
        id: 'I023',
        fecha: '08/04/2025',
        hora: '18:01',
        edad: 61,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P008'
    },
    {
        id: 'I024',
        fecha: '21/03/2025',
        hora: '9:09',
        edad: 71,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P015'
    },
    {
        id: 'I025',
        fecha: '04/05/2025',
        hora: '18:30',
        edad: 69,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I026',
        fecha: '03/05/2025',
        hora: '15:02',
        edad: 71,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P010'
    },
    {
        id: 'I027',
        fecha: '08/03/2025',
        hora: '10:32',
        edad: 61,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P006'
    },
    {
        id: 'I028',
        fecha: '14/03/2025',
        hora: '11:41',
        edad: 23,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P009'
    },
    {
        id: 'I029',
        fecha: '24/02/2025',
        hora: '15:10',
        edad: 37,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P014'
    },
    {
        id: 'I030',
        fecha: '19/04/2025',
        hora: '16:12',
        edad: 77,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I031',
        fecha: '23/01/2025',
        hora: '14:48',
        edad: 45,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P017'
    },
    {
        id: 'I032',
        fecha: '25/01/2025',
        hora: '16:06',
        edad: 18,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I033',
        fecha: '14/03/2025',
        hora: '16:47',
        edad: 66,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P010'
    },
    {
        id: 'I034',
        fecha: '07/03/2025',
        hora: '17:18',
        edad: 42,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I035',
        fecha: '12/01/2025',
        hora: '14:32',
        edad: 63,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I036',
        fecha: '22/01/2025',
        hora: '16:45',
        edad: 80,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I037',
        fecha: '23/03/2025',
        hora: '12:10',
        edad: 45,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I038',
        fecha: '09/01/2025',
        hora: '11:17',
        edad: 59,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I039',
        fecha: '27/01/2025',
        hora: '18:21',
        edad: 41,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I040',
        fecha: '14/03/2025',
        hora: '16:06',
        edad: 42,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P017'
    },
    {
        id: 'I041',
        fecha: '16/02/2025',
        hora: '13:38',
        edad: 43,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I042',
        fecha: '07/03/2025',
        hora: '10:57',
        edad: 37,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P009'
    },
    {
        id: 'I043',
        fecha: '19/03/2025',
        hora: '17:41',
        edad: 22,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I044',
        fecha: '20/03/2025',
        hora: '15:22',
        edad: 65,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I045',
        fecha: '11/01/2025',
        hora: '10:40',
        edad: 31,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P017'
    },
    {
        id: 'I046',
        fecha: '07/04/2025',
        hora: '8:26',
        edad: 63,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P020'
    },
    {
        id: 'I047',
        fecha: '28/01/2025',
        hora: '16:54',
        edad: 21,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P011'
    },
    {
        id: 'I048',
        fecha: '22/02/2025',
        hora: '11:44',
        edad: 77,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P016'
    },
    {
        id: 'I049',
        fecha: '24/03/2025',
        hora: '12:16',
        edad: 52,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I050',
        fecha: '18/02/2025',
        hora: '11:19',
        edad: 77,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P013'
    },
    {
        id: 'I051',
        fecha: '18/02/2025',
        hora: '9:48',
        edad: 61,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I052',
        fecha: '05/02/2025',
        hora: '12:04',
        edad: 44,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I053',
        fecha: '28/01/2025',
        hora: '8:26',
        edad: 30,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P014'
    },
    {
        id: 'I054',
        fecha: '24/04/2025',
        hora: '18:45',
        edad: 61,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I055',
        fecha: '28/04/2025',
        hora: '17:31',
        edad: 29,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P018'
    },
    {
        id: 'I056',
        fecha: '08/05/2025',
        hora: '11:07',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P002'
    },
    {
        id: 'I057',
        fecha: '20/02/2025',
        hora: '11:08',
        edad: 72,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I058',
        fecha: '14/01/2025',
        hora: '17:41',
        edad: 73,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I059',
        fecha: '13/04/2025',
        hora: '14:34',
        edad: 42,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I060',
        fecha: '10/02/2025',
        hora: '11:05',
        edad: 78,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P003'
    },
    {
        id: 'I061',
        fecha: '12/04/2025',
        hora: '17:55',
        edad: 30,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P012'
    },
    {
        id: 'I062',
        fecha: '09/04/2025',
        hora: '12:44',
        edad: 72,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I063',
        fecha: '30/01/2025',
        hora: '14:22',
        edad: 80,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I064',
        fecha: '13/05/2025',
        hora: '11:35',
        edad: 42,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P015'
    },
    {
        id: 'I065',
        fecha: '14/04/2025',
        hora: '8:58',
        edad: 40,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P016'
    },
    {
        id: 'I066',
        fecha: '03/02/2025',
        hora: '13:29',
        edad: 43,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I067',
        fecha: '10/03/2025',
        hora: '11:47',
        edad: 68,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P006'
    },
    {
        id: 'I068',
        fecha: '08/04/2025',
        hora: '10:23',
        edad: 33,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I069',
        fecha: '11/02/2025',
        hora: '12:39',
        edad: 73,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P010'
    },
    {
        id: 'I070',
        fecha: '02/01/2025',
        hora: '17:35',
        edad: 67,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I071',
        fecha: '01/05/2025',
        hora: '13:12',
        edad: 22,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I072',
        fecha: '04/02/2025',
        hora: '12:09',
        edad: 60,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P015'
    },
    {
        id: 'I073',
        fecha: '08/02/2025',
        hora: '16:15',
        edad: 25,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P005'
    },
    {
        id: 'I074',
        fecha: '06/01/2025',
        hora: '9:27',
        edad: 25,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I075',
        fecha: '22/03/2025',
        hora: '11:55',
        edad: 22,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P016'
    },
    {
        id: 'I076',
        fecha: '31/03/2025',
        hora: '12:01',
        edad: 18,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I077',
        fecha: '15/01/2025',
        hora: '8:02',
        edad: 46,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I078',
        fecha: '16/03/2025',
        hora: '11:58',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P001'
    },
    {
        id: 'I079',
        fecha: '24/04/2025',
        hora: '14:49',
        edad: 18,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P005'
    },
    {
        id: 'I080',
        fecha: '09/05/2025',
        hora: '9:26',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P001'
    },
    {
        id: 'I081',
        fecha: '15/01/2025',
        hora: '15:31',
        edad: 18,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I082',
        fecha: '26/01/2025',
        hora: '13:23',
        edad: 78,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P015'
    },
    {
        id: 'I083',
        fecha: '26/01/2025',
        hora: '18:08',
        edad: 37,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P012'
    },
    {
        id: 'I084',
        fecha: '01/01/2025',
        hora: '11:46',
        edad: 75,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P019'
    },
    {
        id: 'I085',
        fecha: '19/04/2025',
        hora: '18:13',
        edad: 67,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P016'
    },
    {
        id: 'I086',
        fecha: '19/04/2025',
        hora: '15:23',
        edad: 67,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P015'
    },
    {
        id: 'I087',
        fecha: '16/01/2025',
        hora: '8:06',
        edad: 72,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I088',
        fecha: '09/05/2025',
        hora: '8:25',
        edad: 65,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P004'
    },
    {
        id: 'I089',
        fecha: '26/01/2025',
        hora: '14:28',
        edad: 49,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I090',
        fecha: '08/04/2025',
        hora: '8:49',
        edad: 42,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P010'
    },
    {
        id: 'I091',
        fecha: '23/04/2025',
        hora: '17:41',
        edad: 72,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P010'
    },
    {
        id: 'I092',
        fecha: '15/02/2025',
        hora: '18:47',
        edad: 23,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P008'
    },
    {
        id: 'I093',
        fecha: '29/04/2025',
        hora: '17:11',
        edad: 58,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P014'
    },
    {
        id: 'I094',
        fecha: '08/05/2025',
        hora: '8:37',
        edad: 27,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P016'
    },
    {
        id: 'I095',
        fecha: '06/05/2025',
        hora: '13:17',
        edad: 76,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I096',
        fecha: '03/01/2025',
        hora: '18:45',
        edad: 40,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P014'
    },
    {
        id: 'I097',
        fecha: '06/04/2025',
        hora: '12:51',
        edad: 49,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I098',
        fecha: '10/02/2025',
        hora: '17:15',
        edad: 73,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P004'
    },
    {
        id: 'I099',
        fecha: '18/01/2025',
        hora: '17:03',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P002'
    },
    {
        id: 'I100',
        fecha: '08/03/2025',
        hora: '10:59',
        edad: 29,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P006'
    },
    {
        id: 'I101',
        fecha: '09/05/2025',
        hora: '8:52',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P001'
    },
    {
        id: 'I102',
        fecha: '06/05/2025',
        hora: '12:16',
        edad: 53,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P017'
    },
    {
        id: 'I103',
        fecha: '09/01/2025',
        hora: '9:09',
        edad: 49,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I104',
        fecha: '13/04/2025',
        hora: '13:21',
        edad: 64,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I105',
        fecha: '06/04/2025',
        hora: '16:41',
        edad: 25,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P013'
    },
    {
        id: 'I106',
        fecha: '05/05/2025',
        hora: '12:13',
        edad: 38,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I107',
        fecha: '18/04/2025',
        hora: '11:35',
        edad: 59,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I108',
        fecha: '08/02/2025',
        hora: '10:15',
        edad: 61,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I109',
        fecha: '02/02/2025',
        hora: '15:58',
        edad: 20,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P007'
    },
    {
        id: 'I110',
        fecha: '11/03/2025',
        hora: '18:52',
        edad: 24,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P008'
    },
    {
        id: 'I111',
        fecha: '13/02/2025',
        hora: '14:37',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P002'
    },
    {
        id: 'I112',
        fecha: '04/01/2025',
        hora: '14:04',
        edad: 42,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P010'
    },
    {
        id: 'I113',
        fecha: '10/04/2025',
        hora: '14:47',
        edad: 46,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P012'
    },
    {
        id: 'I114',
        fecha: '07/05/2025',
        hora: '14:40',
        edad: 19,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I115',
        fecha: '03/05/2025',
        hora: '16:48',
        edad: 55,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I116',
        fecha: '28/01/2025',
        hora: '10:16',
        edad: 64,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I117',
        fecha: '28/01/2025',
        hora: '16:18',
        edad: 34,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I118',
        fecha: '09/01/2025',
        hora: '18:29',
        edad: 68,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P009'
    },
    {
        id: 'I119',
        fecha: '20/03/2025',
        hora: '8:37',
        edad: 41,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I120',
        fecha: '12/04/2025',
        hora: '11:40',
        edad: 77,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I121',
        fecha: '27/01/2025',
        hora: '13:10',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P002'
    },
    {
        id: 'I122',
        fecha: '05/04/2025',
        hora: '18:18',
        edad: 45,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I123',
        fecha: '26/03/2025',
        hora: '8:24',
        edad: 61,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P019'
    },
    {
        id: 'I124',
        fecha: '18/01/2025',
        hora: '9:08',
        edad: 63,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P011'
    },
    {
        id: 'I125',
        fecha: '15/02/2025',
        hora: '17:51',
        edad: 42,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P020'
    },
    {
        id: 'I126',
        fecha: '19/01/2025',
        hora: '12:39',
        edad: 64,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I127',
        fecha: '26/02/2025',
        hora: '13:08',
        edad: 48,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P003'
    },
    {
        id: 'I128',
        fecha: '27/01/2025',
        hora: '13:36',
        edad: 73,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I129',
        fecha: '03/02/2025',
        hora: '18:06',
        edad: 33,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P006'
    },
    {
        id: 'I130',
        fecha: '15/04/2025',
        hora: '14:31',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P001'
    },
    {
        id: 'I131',
        fecha: '28/01/2025',
        hora: '13:28',
        edad: 52,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P013'
    },
    {
        id: 'I132',
        fecha: '19/04/2025',
        hora: '13:24',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P015'
    },
    {
        id: 'I133',
        fecha: '04/01/2025',
        hora: '10:17',
        edad: 33,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P004'
    },
    {
        id: 'I134',
        fecha: '21/04/2025',
        hora: '16:40',
        edad: 44,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P017'
    },
    {
        id: 'I135',
        fecha: '12/02/2025',
        hora: '8:52',
        edad: 40,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P006'
    },
    {
        id: 'I136',
        fecha: '24/04/2025',
        hora: '9:51',
        edad: 26,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P004'
    },
    {
        id: 'I137',
        fecha: '30/01/2025',
        hora: '9:53',
        edad: 31,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P017'
    },
    {
        id: 'I138',
        fecha: '21/01/2025',
        hora: '10:18',
        edad: 56,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I139',
        fecha: '26/03/2025',
        hora: '11:06',
        edad: 48,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I140',
        fecha: '16/03/2025',
        hora: '10:52',
        edad: 73,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P020'
    },
    {
        id: 'I141',
        fecha: '01/03/2025',
        hora: '15:22',
        edad: 66,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P007'
    },
    {
        id: 'I142',
        fecha: '29/03/2025',
        hora: '15:02',
        edad: 24,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I143',
        fecha: '09/05/2025',
        hora: '16:35',
        edad: 27,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P010'
    },
    {
        id: 'I144',
        fecha: '28/03/2025',
        hora: '15:51',
        edad: 22,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P004'
    },
    {
        id: 'I145',
        fecha: '22/02/2025',
        hora: '16:12',
        edad: 66,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I146',
        fecha: '18/02/2025',
        hora: '13:42',
        edad: 58,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I147',
        fecha: '21/04/2025',
        hora: '18:51',
        edad: 33,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I148',
        fecha: '03/02/2025',
        hora: '14:29',
        edad: 44,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I149',
        fecha: '28/02/2025',
        hora: '9:20',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P011'
    },
    {
        id: 'I150',
        fecha: '10/01/2025',
        hora: '14:50',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P002'
    },
    {
        id: 'I151',
        fecha: '17/02/2025',
        hora: '14:52',
        edad: 38,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P007'
    },
    {
        id: 'I152',
        fecha: '24/01/2025',
        hora: '15:55',
        edad: 31,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P003'
    },
    {
        id: 'I153',
        fecha: '29/03/2025',
        hora: '9:55',
        edad: 23,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P013'
    },
    {
        id: 'I154',
        fecha: '13/02/2025',
        hora: '14:10',
        edad: 26,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P016'
    },
    {
        id: 'I155',
        fecha: '05/01/2025',
        hora: '13:18',
        edad: 18,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P014'
    },
    {
        id: 'I156',
        fecha: '24/04/2025',
        hora: '11:02',
        edad: 28,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I157',
        fecha: '17/04/2025',
        hora: '8:14',
        edad: 55,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P003'
    },
    {
        id: 'I158',
        fecha: '25/03/2025',
        hora: '13:12',
        edad: 46,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P015'
    },
    {
        id: 'I159',
        fecha: '25/01/2025',
        hora: '12:30',
        edad: 75,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I160',
        fecha: '05/05/2025',
        hora: '17:12',
        edad: 73,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I161',
        fecha: '27/03/2025',
        hora: '10:39',
        edad: 35,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P014'
    },
    {
        id: 'I162',
        fecha: '04/04/2025',
        hora: '17:11',
        edad: 77,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I163',
        fecha: '01/05/2025',
        hora: '10:29',
        edad: 43,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I164',
        fecha: '21/02/2025',
        hora: '18:45',
        edad: 67,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P020'
    },
    {
        id: 'I165',
        fecha: '21/04/2025',
        hora: '18:51',
        edad: 25,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I166',
        fecha: '06/05/2025',
        hora: '12:28',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P005'
    },
    {
        id: 'I167',
        fecha: '23/03/2025',
        hora: '13:43',
        edad: 61,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I168',
        fecha: '27/04/2025',
        hora: '10:04',
        edad: 49,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P012'
    },
    {
        id: 'I169',
        fecha: '15/01/2025',
        hora: '13:49',
        edad: 28,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I170',
        fecha: '19/04/2025',
        hora: '8:36',
        edad: 72,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P008'
    },
    {
        id: 'I171',
        fecha: '04/03/2025',
        hora: '16:25',
        edad: 72,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P018'
    },
    {
        id: 'I172',
        fecha: '29/01/2025',
        hora: '15:59',
        edad: 33,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P012'
    },
    {
        id: 'I173',
        fecha: '25/01/2025',
        hora: '9:41',
        edad: 28,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P017'
    },
    {
        id: 'I174',
        fecha: '19/01/2025',
        hora: '9:14',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P002'
    },
    {
        id: 'I175',
        fecha: '02/03/2025',
        hora: '18:29',
        edad: 80,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P013'
    },
    {
        id: 'I176',
        fecha: '30/04/2025',
        hora: '17:27',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P007'
    },
    {
        id: 'I177',
        fecha: '16/03/2025',
        hora: '8:46',
        edad: 41,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P018'
    },
    {
        id: 'I178',
        fecha: '28/04/2025',
        hora: '8:20',
        edad: 27,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I179',
        fecha: '05/03/2025',
        hora: '8:43',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P001'
    },
    {
        id: 'I180',
        fecha: '05/02/2025',
        hora: '15:28',
        edad: 72,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P009'
    },
    {
        id: 'I181',
        fecha: '17/02/2025',
        hora: '17:18',
        edad: 79,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P011'
    },
    {
        id: 'I182',
        fecha: '10/03/2025',
        hora: '12:20',
        edad: 63,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P012'
    },
    {
        id: 'I183',
        fecha: '19/02/2025',
        hora: '8:10',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P002'
    },
    {
        id: 'I184',
        fecha: '27/04/2025',
        hora: '11:34',
        edad: 68,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P006'
    },
    {
        id: 'I185',
        fecha: '03/03/2025',
        hora: '16:13',
        edad: 30,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P010'
    },
    {
        id: 'I186',
        fecha: '05/05/2025',
        hora: '16:12',
        edad: 36,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P019'
    },
    {
        id: 'I187',
        fecha: '09/01/2025',
        hora: '16:10',
        edad: 52,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P012'
    },
    {
        id: 'I188',
        fecha: '29/01/2025',
        hora: '16:01',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P001'
    },
    {
        id: 'I189',
        fecha: '08/04/2025',
        hora: '14:05',
        edad: 67,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I190',
        fecha: '16/02/2025',
        hora: '13:23',
        edad: 33,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P015'
    },
    {
        id: 'I191',
        fecha: '01/02/2025',
        hora: '11:22',
        edad: 75,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I192',
        fecha: '25/04/2025',
        hora: '15:23',
        edad: 69,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I193',
        fecha: '12/04/2025',
        hora: '12:37',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P002'
    },
    {
        id: 'I194',
        fecha: '07/02/2025',
        hora: '13:51',
        edad: 31,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I195',
        fecha: '27/03/2025',
        hora: '10:48',
        edad: 19,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P012'
    },
    {
        id: 'I196',
        fecha: '05/02/2025',
        hora: '14:19',
        edad: 36,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P003'
    },
    {
        id: 'I197',
        fecha: '14/01/2025',
        hora: '10:57',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P002'
    },
    {
        id: 'I198',
        fecha: '11/01/2025',
        hora: '11:57',
        edad: 58,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I199',
        fecha: '25/04/2025',
        hora: '14:54',
        edad: 18,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P009'
    },
    {
        id: 'I200',
        fecha: '03/05/2025',
        hora: '8:09',
        edad: 35,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I201',
        fecha: '19/01/2025',
        hora: '17:59',
        edad: 33,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I202',
        fecha: '26/03/2025',
        hora: '8:24',
        edad: 54,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I203',
        fecha: '02/01/2025',
        hora: '12:02',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P001'
    },
    {
        id: 'I204',
        fecha: '07/02/2025',
        hora: '8:25',
        edad: 64,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I205',
        fecha: '21/01/2025',
        hora: '14:28',
        edad: 37,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P020'
    },
    {
        id: 'I206',
        fecha: '09/02/2025',
        hora: '11:04',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P009'
    },
    {
        id: 'I207',
        fecha: '02/04/2025',
        hora: '14:10',
        edad: 77,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P019'
    },
    {
        id: 'I208',
        fecha: '01/03/2025',
        hora: '16:33',
        edad: 30,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P017'
    },
    {
        id: 'I209',
        fecha: '24/04/2025',
        hora: '18:27',
        edad: 21,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P020'
    },
    {
        id: 'I210',
        fecha: '19/03/2025',
        hora: '15:13',
        edad: 21,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I211',
        fecha: '18/03/2025',
        hora: '8:59',
        edad: 48,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P019'
    },
    {
        id: 'I212',
        fecha: '20/04/2025',
        hora: '18:20',
        edad: 19,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P013'
    },
    {
        id: 'I213',
        fecha: '04/05/2025',
        hora: '9:17',
        edad: 73,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P012'
    },
    {
        id: 'I214',
        fecha: '08/05/2025',
        hora: '9:49',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I215',
        fecha: '02/02/2025',
        hora: '11:54',
        edad: 42,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P005'
    },
    {
        id: 'I216',
        fecha: '24/02/2025',
        hora: '8:22',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P002'
    },
    {
        id: 'I217',
        fecha: '08/05/2025',
        hora: '15:26',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P001'
    },
    {
        id: 'I218',
        fecha: '21/03/2025',
        hora: '10:46',
        edad: 67,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I219',
        fecha: '07/04/2025',
        hora: '14:42',
        edad: 71,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P005'
    },
    {
        id: 'I220',
        fecha: '13/05/2025',
        hora: '8:07',
        edad: 38,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P007'
    },
    {
        id: 'I221',
        fecha: '27/01/2025',
        hora: '12:49',
        edad: 62,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P006'
    },
    {
        id: 'I222',
        fecha: '23/02/2025',
        hora: '13:12',
        edad: 33,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I223',
        fecha: '17/01/2025',
        hora: '11:53',
        edad: 73,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P008'
    },
    {
        id: 'I224',
        fecha: '22/04/2025',
        hora: '10:39',
        edad: 61,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I225',
        fecha: '30/03/2025',
        hora: '11:58',
        edad: 44,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I226',
        fecha: '24/01/2025',
        hora: '17:32',
        edad: 23,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I227',
        fecha: '05/01/2025',
        hora: '13:57',
        edad: 61,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P012'
    },
    {
        id: 'I228',
        fecha: '14/03/2025',
        hora: '10:43',
        edad: 51,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P004'
    },
    {
        id: 'I229',
        fecha: '14/02/2025',
        hora: '8:19',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P001'
    },
    {
        id: 'I230',
        fecha: '05/03/2025',
        hora: '8:04',
        edad: 37,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P018'
    },
    {
        id: 'I231',
        fecha: '27/01/2025',
        hora: '17:49',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P002'
    },
    {
        id: 'I232',
        fecha: '09/01/2025',
        hora: '18:28',
        edad: 25,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P008'
    },
    {
        id: 'I233',
        fecha: '28/01/2025',
        hora: '13:47',
        edad: 77,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P005'
    },
    {
        id: 'I234',
        fecha: '11/03/2025',
        hora: '14:38',
        edad: 40,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P014'
    },
    {
        id: 'I235',
        fecha: '18/02/2025',
        hora: '18:42',
        edad: 23,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P009'
    },
    {
        id: 'I236',
        fecha: '14/02/2025',
        hora: '16:21',
        edad: 44,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P006'
    },
    {
        id: 'I237',
        fecha: '04/01/2025',
        hora: '12:56',
        edad: 36,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P017'
    },
    {
        id: 'I238',
        fecha: '11/02/2025',
        hora: '10:16',
        edad: 54,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P015'
    },
    {
        id: 'I239',
        fecha: '31/03/2025',
        hora: '8:16',
        edad: 29,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P012'
    },
    {
        id: 'I240',
        fecha: '10/04/2025',
        hora: '9:11',
        edad: 59,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P003'
    },
    {
        id: 'I241',
        fecha: '30/03/2025',
        hora: '12:47',
        edad: 36,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I242',
        fecha: '06/04/2025',
        hora: '15:18',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P013'
    },
    {
        id: 'I243',
        fecha: '13/05/2025',
        hora: '14:15',
        edad: 66,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P005'
    },
    {
        id: 'I244',
        fecha: '08/04/2025',
        hora: '10:08',
        edad: 41,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P013'
    },
    {
        id: 'I245',
        fecha: '24/04/2025',
        hora: '11:10',
        edad: 21,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I246',
        fecha: '15/01/2025',
        hora: '8:42',
        edad: 38,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I247',
        fecha: '07/01/2025',
        hora: '15:07',
        edad: 32,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P001'
    },
    {
        id: 'I248',
        fecha: '28/03/2025',
        hora: '15:23',
        edad: 57,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I249',
        fecha: '10/05/2025',
        hora: '12:46',
        edad: 63,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P013'
    },
    {
        id: 'I250',
        fecha: '04/03/2025',
        hora: '11:32',
        edad: 65,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I251',
        fecha: '11/01/2025',
        hora: '8:39',
        edad: 25,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I252',
        fecha: '10/05/2025',
        hora: '14:06',
        edad: 49,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P003'
    },
    {
        id: 'I253',
        fecha: '03/04/2025',
        hora: '13:55',
        edad: 54,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P014'
    },
    {
        id: 'I254',
        fecha: '03/01/2025',
        hora: '13:15',
        edad: 53,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P003'
    },
    {
        id: 'I255',
        fecha: '06/04/2025',
        hora: '17:49',
        edad: 18,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P011'
    },
    {
        id: 'I256',
        fecha: '11/05/2025',
        hora: '15:28',
        edad: 67,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I257',
        fecha: '13/02/2025',
        hora: '16:40',
        edad: 24,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P017'
    },
    {
        id: 'I258',
        fecha: '09/05/2025',
        hora: '9:05',
        edad: 77,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P008'
    },
    {
        id: 'I259',
        fecha: '29/04/2025',
        hora: '10:45',
        edad: 38,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I260',
        fecha: '10/05/2025',
        hora: '13:12',
        edad: 79,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P016'
    },
    {
        id: 'I261',
        fecha: '04/04/2025',
        hora: '11:31',
        edad: 31,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I262',
        fecha: '21/03/2025',
        hora: '14:16',
        edad: 59,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P019'
    },
    {
        id: 'I263',
        fecha: '19/02/2025',
        hora: '14:25',
        edad: 47,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P008'
    },
    {
        id: 'I264',
        fecha: '10/05/2025',
        hora: '16:57',
        edad: 48,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P003'
    },
    {
        id: 'I265',
        fecha: '07/03/2025',
        hora: '11:09',
        edad: 79,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P009'
    },
    {
        id: 'I266',
        fecha: '11/05/2025',
        hora: '16:18',
        edad: 59,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P019'
    },
    {
        id: 'I267',
        fecha: '23/03/2025',
        hora: '10:05',
        edad: 46,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P014'
    },
    {
        id: 'I268',
        fecha: '04/01/2025',
        hora: '16:47',
        edad: 66,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P004'
    },
    {
        id: 'I269',
        fecha: '31/01/2025',
        hora: '13:49',
        edad: 65,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P007'
    },
    {
        id: 'I270',
        fecha: '11/04/2025',
        hora: '17:39',
        edad: 60,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P009'
    },
    {
        id: 'I271',
        fecha: '20/04/2025',
        hora: '13:40',
        edad: 32,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P001'
    },
    {
        id: 'I272',
        fecha: '25/02/2025',
        hora: '8:28',
        edad: 73,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P016'
    },
    {
        id: 'I273',
        fecha: '28/03/2025',
        hora: '14:25',
        edad: 28,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P010'
    },
    {
        id: 'I274',
        fecha: '19/03/2025',
        hora: '18:54',
        edad: 79,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P004'
    },
    {
        id: 'I275',
        fecha: '12/01/2025',
        hora: '8:19',
        edad: 55,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P012'
    },
    {
        id: 'I276',
        fecha: '09/01/2025',
        hora: '14:51',
        edad: 31,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P020'
    },
    {
        id: 'I277',
        fecha: '04/03/2025',
        hora: '16:18',
        edad: 46,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P009'
    },
    {
        id: 'I278',
        fecha: '05/01/2025',
        hora: '14:08',
        edad: 73,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P014'
    },
    {
        id: 'I279',
        fecha: '16/01/2025',
        hora: '14:39',
        edad: 50,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P004'
    },
    {
        id: 'I280',
        fecha: '21/01/2025',
        hora: '15:37',
        edad: 77,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P019'
    },
    {
        id: 'I281',
        fecha: '13/03/2025',
        hora: '8:26',
        edad: 73,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P011'
    },
    {
        id: 'I282',
        fecha: '01/02/2025',
        hora: '9:51',
        edad: 77,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P005'
    },
    {
        id: 'I283',
        fecha: '09/05/2025',
        hora: '16:50',
        edad: 54,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P008'
    },
    {
        id: 'I284',
        fecha: '10/04/2025',
        hora: '9:41',
        edad: 61,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P018'
    },
    {
        id: 'I285',
        fecha: '24/02/2025',
        hora: '10:03',
        edad: 47,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P008'
    },
    {
        id: 'I286',
        fecha: '18/01/2025',
        hora: '9:47',
        edad: 18,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P010'
    },
    {
        id: 'I287',
        fecha: '18/01/2025',
        hora: '8:14',
        edad: 31,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P009'
    },
    {
        id: 'I288',
        fecha: '06/04/2025',
        hora: '8:01',
        edad: 37,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P011'
    },
    {
        id: 'I289',
        fecha: '30/01/2025',
        hora: '14:24',
        edad: 32,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P002'
    },
    {
        id: 'I290',
        fecha: '21/02/2025',
        hora: '18:54',
        edad: 71,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P005'
    },
    {
        id: 'I291',
        fecha: '15/04/2025',
        hora: '10:17',
        edad: 78,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Proliferativo',
        paciente: 'P011'
    },
    {
        id: 'I292',
        fecha: '17/03/2025',
        hora: '12:27',
        edad: 29,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Moderado',
        paciente: 'P016'
    },
    {
        id: 'I293',
        fecha: '05/05/2025',
        hora: '18:51',
        edad: 66,
        afeccion: 'DMAE Húmeda',
        ojo: 'Derecho',
        resultado: 'Leve',
        paciente: 'P003'
    },
    {
        id: 'I294',
        fecha: '11/03/2025',
        hora: '12:38',
        edad: 27,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P007'
    },
    {
        id: 'I295',
        fecha: '20/03/2025',
        hora: '17:53',
        edad: 79,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Sin Afección',
        paciente: 'P009'
    },
    {
        id: 'I296',
        fecha: '01/01/2025',
        hora: '11:10',
        edad: 31,
        afeccion: 'DMAE Seca',
        ojo: 'Izquierdo',
        resultado: 'Moderado',
        paciente: 'P018'
    },
    {
        id: 'I297',
        fecha: '04/03/2025',
        hora: '13:25',
        edad: 29,
        afeccion: 'DMAE Húmeda',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P010'
    },
    {
        id: 'I298',
        fecha: '26/01/2025',
        hora: '17:50',
        edad: 34,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Izquierdo',
        resultado: 'Leve',
        paciente: 'P012'
    },
    {
        id: 'I299',
        fecha: '18/02/2025',
        hora: '9:07',
        edad: 18,
        afeccion: 'DMAE Seca',
        ojo: 'Derecho',
        resultado: 'Proliferativo',
        paciente: 'P007'
    },
    {
        id: 'I300',
        fecha: '17/02/2025',
        hora: '17:09',
        edad: 71,
        afeccion: 'Retinopatía Diabética',
        ojo: 'Derecho',
        resultado: 'Sin Afección',
        paciente: 'P014'
    }
];

export function findPatient(id: string): any {
    return patients.find((p: any) => p.clave === id);
}
